// #169: llama.cpp's MMQ instance for IQ1_M. Its template-instances/ has none, because the IQ1_M tile is ours
// (third_party/ggml/patches/0001-mmq-iq1_m.patch, applied to the pinned checkout by CMakeLists.txt). The file has the
// same shape as an autogenerated template-instances/mmq-instance-*.cu.
#include "mmq.cuh"

DECL_MMQ_CASE(GGML_TYPE_IQ1_M);
